config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :bookmarks

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  validates_presence_of :title, :link
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def index
    @bookmarks = Bookmark.all
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    if @bookmark.save
      redirect_to url_for(bookmarks_path)
    else
      render 'new'
    end
  end

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  def update
    @bookmark = Bookmark.find(params[:id])

    if @bookmark.update(bookmark_params)
      redirect_to url_for(bookmarks_path)
    else
      render 'edit'
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to url_for(bookmarks_path)
  end

  private
    def bookmark_params
      params.require(:bookmark).permit(:title, :link, :summary)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmark_helper.rb
module BookmarkHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/bookmarks/_form.html.erb
<%= form_for @bookmark do |f| %>
  <% if @bookmark.errors.any? %>
    <p>
      <%= pluralize(@bookmark.errors.count, "error") %>
      prohibited this article from being saved:
    </p>
    <ul>
      <% @bookmark.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <p>
    <%= f.label "标题" %><br/>
    <%= f.text_field :title, size: 64 %>
  </p>
  <p>
    <%= f.label "链接" %><br/>
    <%= f.text_field :link, size: 64 %>
  </p>
  <p>
    <%= f.label "摘要" %><br/>
    <%= f.text_field :summary, size: 64 %>
  </p>
  <p>
    <%= f.submit class: "btn btn-primary" %>
  </p>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

<hr/>
<a href="<%= bookmarks_path %>">Bookmarks</a> | <a href="<%= root_path %>">Back to home</a>

app/views/bookmarks/index.html.erb
<h1>Deadlining - Bookmarks</h1>

<table class="table table-hover">
  <tr>
    <th>标题</th>
    <th>摘要</th>
    <th>维护操作</th>
  </tr>
  <% @bookmarks.each do |bookmark| %>
    <tr>
      <td><a href="<%= bookmark.link %>"><%= bookmark.title %></a></td>
      <td><%= bookmark.summary %></td>
      <td>
        <%= link_to "查看", bookmark_path(bookmark) %> |
        <%= link_to "编辑", edit_bookmark_path(bookmark) %> |
        <%= link_to "删除", bookmark_path(bookmark), method: :delete, data: {confirm: '确定要删除吗?'} %>
      </td>
    </tr>
  <% end %>
</table>

<hr/>
<a href="<%= new_bookmark_path %>">Favorites a link</a> | <a href="<%= root_path %>">Back to home</a>

app/views/bookmarks/new.html.erb
<h1>Favorite a link</h1>
<%= render 'form' %>
<hr/>
<a href="<%= bookmarks_path %>">Bookmarks</a> | <a href="<%= root_path %>">Back to home</a>

app/views/bookmarks/show.html.erb
<h1>Show</h1>

<table class="table table-hover">
  <tr>
    <th>标题</th>
    <th>连接</th>
    <th>摘要</th>
  </tr>
  <tr>
    <td><%= @bookmark.title %></td>
    <td><a href="<%= @bookmark.link %>"><%= @bookmark.link %></a></td>
    <td><%= @bookmark.summary %></td>
  </tr>
</table>

<hr/>
<%= link_to 'Bookmarks', bookmarks_path %> | <%= link_to 'Back to home', root_path %>

app/views/home/index.html.erb
<h1>Deadlining</h1>
<a href="<%= bookmarks_path %>">Bookmarks</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Deadlining</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
<%= yield %>
</div>

</body>
</html>